import {
  ArrowFatLineDown,
  Brain,
  BookBookmark,
  Books,
  CalendarBlank,
  CalendarCheck,
  CalendarDots,
  CalendarPlus,
  CalendarStar,
  Certificate,
  CircleHalf,
  Compass,
  Confetti,
  Crown,
  Drop,
  Flag,
  Flame,
  Flower,
  Gavel,
  HandHeart,
  Handshake,
  HandWaving,
  Heart,
  Hourglass,
  ListChecks,
  ListNumbers,
  Moon,
  MoonStars,
  Mountains,
  Rewind,
  Shield,
  ShieldCheck,
  SpeakerHigh,
  Stack,
  Star,
  Sun,
  SunDim,
  SunHorizon,
  Trophy,
  UsersThree,
  type Icon,
} from "@phosphor-icons/react"
import { Kaaba } from "../components/icons"

export const DEED_ICONS: Record<string, Icon> = {
  // Salah
  deed_salah_001: Kaaba,
  deed_salah_002: UsersThree,
  deed_salah_004: Stack,
  deed_salah_005: SunHorizon,
  deed_salah_006: Star,
  deed_salah_007: MoonStars,
  deed_salah_008: Sun,
  deed_salah_009: HandWaving,
  deed_salah_010: Drop,
  deed_salah_011: Compass,
  deed_salah_012: Heart,
  deed_salah_013: CalendarCheck,
  deed_salah_017: SunDim,
  deed_salah_018: Flower,
  deed_salah_019: ArrowFatLineDown,
  deed_salah_020: HandHeart,

  // Qur'an
  deed_quran_001: BookBookmark,
  deed_quran_003: Books,
  deed_quran_004: Moon,
  deed_quran_005: Crown,
  deed_quran_006: ShieldCheck,
  deed_quran_007: SpeakerHigh,
  deed_quran_008: Shield,
  deed_quran_009: Brain,
  deed_quran_010: Rewind,
  deed_quran_014: ListNumbers,
  deed_quran_015: Flame,

  // Fasting
  deed_fasting_001: CalendarStar,
  deed_fasting_002: CalendarBlank,
  deed_fasting_003: CircleHalf,
  deed_fasting_004: Mountains,
  deed_fasting_005: Flag,
  deed_fasting_006: Confetti,
  deed_fasting_007: Hourglass,
  deed_fasting_008: CalendarPlus,
  deed_fasting_009: Trophy,
  deed_fasting_010: CalendarDots,
  deed_fasting_011: ListChecks,
  deed_fasting_012: Certificate,
  deed_fasting_013: Gavel,
  deed_fasting_014: ShieldCheck,
  deed_fasting_015: Handshake,
}
