export interface Surah {
  number: number
  nameArabic: string
  nameTransliteration: string
  nameMeaning: string
  verseCount: number
  revelation: "Meccan" | "Medinan"
}

export interface QuranAttachment {
  surahNumber: number
  surahName: string
  fromAyah: number
  toAyah: number
}

// Standard 114-surah list — names, verse counts (Uthmani/standard count), and
// revelation place are all fixed reference facts, not app-specific data.
export const SURAHS: Surah[] = [
  { number: 1, nameArabic: "الفاتحة", nameTransliteration: "Al-Fatihah", nameMeaning: "The Opening", verseCount: 7, revelation: "Meccan" },
  { number: 2, nameArabic: "البقرة", nameTransliteration: "Al-Baqarah", nameMeaning: "The Cow", verseCount: 286, revelation: "Medinan" },
  { number: 3, nameArabic: "آل عمران", nameTransliteration: "Ali 'Imran", nameMeaning: "Family of Imran", verseCount: 200, revelation: "Medinan" },
  { number: 4, nameArabic: "النساء", nameTransliteration: "An-Nisa", nameMeaning: "The Women", verseCount: 176, revelation: "Medinan" },
  { number: 5, nameArabic: "المائدة", nameTransliteration: "Al-Ma'idah", nameMeaning: "The Table Spread", verseCount: 120, revelation: "Medinan" },
  { number: 6, nameArabic: "الأنعام", nameTransliteration: "Al-An'am", nameMeaning: "The Cattle", verseCount: 165, revelation: "Meccan" },
  { number: 7, nameArabic: "الأعراف", nameTransliteration: "Al-A'raf", nameMeaning: "The Heights", verseCount: 206, revelation: "Meccan" },
  { number: 8, nameArabic: "الأنفال", nameTransliteration: "Al-Anfal", nameMeaning: "The Spoils of War", verseCount: 75, revelation: "Medinan" },
  { number: 9, nameArabic: "التوبة", nameTransliteration: "At-Tawbah", nameMeaning: "The Repentance", verseCount: 129, revelation: "Medinan" },
  { number: 10, nameArabic: "يونس", nameTransliteration: "Yunus", nameMeaning: "Jonah", verseCount: 109, revelation: "Meccan" },
  { number: 11, nameArabic: "هود", nameTransliteration: "Hud", nameMeaning: "Hud", verseCount: 123, revelation: "Meccan" },
  { number: 12, nameArabic: "يوسف", nameTransliteration: "Yusuf", nameMeaning: "Joseph", verseCount: 111, revelation: "Meccan" },
  { number: 13, nameArabic: "الرعد", nameTransliteration: "Ar-Ra'd", nameMeaning: "The Thunder", verseCount: 43, revelation: "Medinan" },
  { number: 14, nameArabic: "ابراهيم", nameTransliteration: "Ibrahim", nameMeaning: "Abraham", verseCount: 52, revelation: "Meccan" },
  { number: 15, nameArabic: "الحجر", nameTransliteration: "Al-Hijr", nameMeaning: "The Rocky Tract", verseCount: 99, revelation: "Meccan" },
  { number: 16, nameArabic: "النحل", nameTransliteration: "An-Nahl", nameMeaning: "The Bee", verseCount: 128, revelation: "Meccan" },
  { number: 17, nameArabic: "الإسراء", nameTransliteration: "Al-Isra", nameMeaning: "The Night Journey", verseCount: 111, revelation: "Meccan" },
  { number: 18, nameArabic: "الكهف", nameTransliteration: "Al-Kahf", nameMeaning: "The Cave", verseCount: 110, revelation: "Meccan" },
  { number: 19, nameArabic: "مريم", nameTransliteration: "Maryam", nameMeaning: "Mary", verseCount: 98, revelation: "Meccan" },
  { number: 20, nameArabic: "طه", nameTransliteration: "Taha", nameMeaning: "Ta-Ha", verseCount: 135, revelation: "Meccan" },
  { number: 21, nameArabic: "الأنبياء", nameTransliteration: "Al-Anbya", nameMeaning: "The Prophets", verseCount: 112, revelation: "Meccan" },
  { number: 22, nameArabic: "الحج", nameTransliteration: "Al-Hajj", nameMeaning: "The Pilgrimage", verseCount: 78, revelation: "Medinan" },
  { number: 23, nameArabic: "المؤمنون", nameTransliteration: "Al-Mu'minun", nameMeaning: "The Believers", verseCount: 118, revelation: "Meccan" },
  { number: 24, nameArabic: "النور", nameTransliteration: "An-Nur", nameMeaning: "The Light", verseCount: 64, revelation: "Medinan" },
  { number: 25, nameArabic: "الفرقان", nameTransliteration: "Al-Furqan", nameMeaning: "The Criterion", verseCount: 77, revelation: "Meccan" },
  { number: 26, nameArabic: "الشعراء", nameTransliteration: "Ash-Shu'ara", nameMeaning: "The Poets", verseCount: 227, revelation: "Meccan" },
  { number: 27, nameArabic: "النمل", nameTransliteration: "An-Naml", nameMeaning: "The Ant", verseCount: 93, revelation: "Meccan" },
  { number: 28, nameArabic: "القصص", nameTransliteration: "Al-Qasas", nameMeaning: "The Stories", verseCount: 88, revelation: "Meccan" },
  { number: 29, nameArabic: "العنكبوت", nameTransliteration: "Al-'Ankabut", nameMeaning: "The Spider", verseCount: 69, revelation: "Meccan" },
  { number: 30, nameArabic: "الروم", nameTransliteration: "Ar-Rum", nameMeaning: "The Romans", verseCount: 60, revelation: "Meccan" },
  { number: 31, nameArabic: "لقمان", nameTransliteration: "Luqman", nameMeaning: "Luqman", verseCount: 34, revelation: "Meccan" },
  { number: 32, nameArabic: "السجدة", nameTransliteration: "As-Sajdah", nameMeaning: "The Prostration", verseCount: 30, revelation: "Meccan" },
  { number: 33, nameArabic: "الأحزاب", nameTransliteration: "Al-Ahzab", nameMeaning: "The Combined Forces", verseCount: 73, revelation: "Medinan" },
  { number: 34, nameArabic: "سبإ", nameTransliteration: "Saba", nameMeaning: "Sheba", verseCount: 54, revelation: "Meccan" },
  { number: 35, nameArabic: "فاطر", nameTransliteration: "Fatir", nameMeaning: "Originator", verseCount: 45, revelation: "Meccan" },
  { number: 36, nameArabic: "يس", nameTransliteration: "Ya-Sin", nameMeaning: "Ya Sin", verseCount: 83, revelation: "Meccan" },
  { number: 37, nameArabic: "الصافات", nameTransliteration: "As-Saffat", nameMeaning: "Those who set the Ranks", verseCount: 182, revelation: "Meccan" },
  { number: 38, nameArabic: "ص", nameTransliteration: "Sad", nameMeaning: "The Letter Sad", verseCount: 88, revelation: "Meccan" },
  { number: 39, nameArabic: "الزمر", nameTransliteration: "Az-Zumar", nameMeaning: "The Troops", verseCount: 75, revelation: "Meccan" },
  { number: 40, nameArabic: "غافر", nameTransliteration: "Ghafir", nameMeaning: "The Forgiver", verseCount: 85, revelation: "Meccan" },
  { number: 41, nameArabic: "فصلت", nameTransliteration: "Fussilat", nameMeaning: "Explained in Detail", verseCount: 54, revelation: "Meccan" },
  { number: 42, nameArabic: "الشورى", nameTransliteration: "Ash-Shuraa", nameMeaning: "The Consultation", verseCount: 53, revelation: "Meccan" },
  { number: 43, nameArabic: "الزخرف", nameTransliteration: "Az-Zukhruf", nameMeaning: "The Ornaments of Gold", verseCount: 89, revelation: "Meccan" },
  { number: 44, nameArabic: "الدخان", nameTransliteration: "Ad-Dukhan", nameMeaning: "The Smoke", verseCount: 59, revelation: "Meccan" },
  { number: 45, nameArabic: "الجاثية", nameTransliteration: "Al-Jathiyah", nameMeaning: "The Crouching", verseCount: 37, revelation: "Meccan" },
  { number: 46, nameArabic: "الأحقاف", nameTransliteration: "Al-Ahqaf", nameMeaning: "The Wind-Curved Sandhills", verseCount: 35, revelation: "Meccan" },
  { number: 47, nameArabic: "محمد", nameTransliteration: "Muhammad", nameMeaning: "Muhammad", verseCount: 38, revelation: "Medinan" },
  { number: 48, nameArabic: "الفتح", nameTransliteration: "Al-Fath", nameMeaning: "The Victory", verseCount: 29, revelation: "Medinan" },
  { number: 49, nameArabic: "الحجرات", nameTransliteration: "Al-Hujurat", nameMeaning: "The Rooms", verseCount: 18, revelation: "Medinan" },
  { number: 50, nameArabic: "ق", nameTransliteration: "Qaf", nameMeaning: "The Letter Qaf", verseCount: 45, revelation: "Meccan" },
  { number: 51, nameArabic: "الذاريات", nameTransliteration: "Adh-Dhariyat", nameMeaning: "The Winnowing Winds", verseCount: 60, revelation: "Meccan" },
  { number: 52, nameArabic: "الطور", nameTransliteration: "At-Tur", nameMeaning: "The Mount", verseCount: 49, revelation: "Meccan" },
  { number: 53, nameArabic: "النجم", nameTransliteration: "An-Najm", nameMeaning: "The Star", verseCount: 62, revelation: "Meccan" },
  { number: 54, nameArabic: "القمر", nameTransliteration: "Al-Qamar", nameMeaning: "The Moon", verseCount: 55, revelation: "Meccan" },
  { number: 55, nameArabic: "الرحمن", nameTransliteration: "Ar-Rahman", nameMeaning: "The Beneficent", verseCount: 78, revelation: "Medinan" },
  { number: 56, nameArabic: "الواقعة", nameTransliteration: "Al-Waqi'ah", nameMeaning: "The Inevitable", verseCount: 96, revelation: "Meccan" },
  { number: 57, nameArabic: "الحديد", nameTransliteration: "Al-Hadid", nameMeaning: "The Iron", verseCount: 29, revelation: "Medinan" },
  { number: 58, nameArabic: "المجادلة", nameTransliteration: "Al-Mujadila", nameMeaning: "The Pleading Woman", verseCount: 22, revelation: "Medinan" },
  { number: 59, nameArabic: "الحشر", nameTransliteration: "Al-Hashr", nameMeaning: "The Exile", verseCount: 24, revelation: "Medinan" },
  { number: 60, nameArabic: "الممتحنة", nameTransliteration: "Al-Mumtahanah", nameMeaning: "She that is to be examined", verseCount: 13, revelation: "Medinan" },
  { number: 61, nameArabic: "الصف", nameTransliteration: "As-Saff", nameMeaning: "The Ranks", verseCount: 14, revelation: "Medinan" },
  { number: 62, nameArabic: "الجمعة", nameTransliteration: "Al-Jumu'ah", nameMeaning: "The Congregation, Friday", verseCount: 11, revelation: "Medinan" },
  { number: 63, nameArabic: "المنافقون", nameTransliteration: "Al-Munafiqun", nameMeaning: "The Hypocrites", verseCount: 11, revelation: "Medinan" },
  { number: 64, nameArabic: "التغابن", nameTransliteration: "At-Taghabun", nameMeaning: "The Mutual Disillusion", verseCount: 18, revelation: "Medinan" },
  { number: 65, nameArabic: "الطلاق", nameTransliteration: "At-Talaq", nameMeaning: "The Divorce", verseCount: 12, revelation: "Medinan" },
  { number: 66, nameArabic: "التحريم", nameTransliteration: "At-Tahrim", nameMeaning: "The Prohibition", verseCount: 12, revelation: "Medinan" },
  { number: 67, nameArabic: "الملك", nameTransliteration: "Al-Mulk", nameMeaning: "The Sovereignty", verseCount: 30, revelation: "Meccan" },
  { number: 68, nameArabic: "القلم", nameTransliteration: "Al-Qalam", nameMeaning: "The Pen", verseCount: 52, revelation: "Meccan" },
  { number: 69, nameArabic: "الحاقة", nameTransliteration: "Al-Haqqah", nameMeaning: "The Reality", verseCount: 52, revelation: "Meccan" },
  { number: 70, nameArabic: "المعارج", nameTransliteration: "Al-Ma'arij", nameMeaning: "The Ascending Stairways", verseCount: 44, revelation: "Meccan" },
  { number: 71, nameArabic: "نوح", nameTransliteration: "Nuh", nameMeaning: "Noah", verseCount: 28, revelation: "Meccan" },
  { number: 72, nameArabic: "الجن", nameTransliteration: "Al-Jinn", nameMeaning: "The Jinn", verseCount: 28, revelation: "Meccan" },
  { number: 73, nameArabic: "المزمل", nameTransliteration: "Al-Muzzammil", nameMeaning: "The Enshrouded One", verseCount: 20, revelation: "Meccan" },
  { number: 74, nameArabic: "المدثر", nameTransliteration: "Al-Muddaththir", nameMeaning: "The Cloaked One", verseCount: 56, revelation: "Meccan" },
  { number: 75, nameArabic: "القيامة", nameTransliteration: "Al-Qiyamah", nameMeaning: "The Resurrection", verseCount: 40, revelation: "Meccan" },
  { number: 76, nameArabic: "الانسان", nameTransliteration: "Al-Insan", nameMeaning: "The Man", verseCount: 31, revelation: "Medinan" },
  { number: 77, nameArabic: "المرسلات", nameTransliteration: "Al-Mursalat", nameMeaning: "The Emissaries", verseCount: 50, revelation: "Meccan" },
  { number: 78, nameArabic: "النبإ", nameTransliteration: "An-Naba", nameMeaning: "The Tidings", verseCount: 40, revelation: "Meccan" },
  { number: 79, nameArabic: "النازعات", nameTransliteration: "An-Nazi'at", nameMeaning: "Those who drag forth", verseCount: 46, revelation: "Meccan" },
  { number: 80, nameArabic: "عبس", nameTransliteration: "'Abasa", nameMeaning: "He Frowned", verseCount: 42, revelation: "Meccan" },
  { number: 81, nameArabic: "التكوير", nameTransliteration: "At-Takwir", nameMeaning: "The Overthrowing", verseCount: 29, revelation: "Meccan" },
  { number: 82, nameArabic: "الإنفطار", nameTransliteration: "Al-Infitar", nameMeaning: "The Cleaving", verseCount: 19, revelation: "Meccan" },
  { number: 83, nameArabic: "المطففين", nameTransliteration: "Al-Mutaffifin", nameMeaning: "The Defrauding", verseCount: 36, revelation: "Meccan" },
  { number: 84, nameArabic: "الإنشقاق", nameTransliteration: "Al-Inshiqaq", nameMeaning: "The Sundering", verseCount: 25, revelation: "Meccan" },
  { number: 85, nameArabic: "البروج", nameTransliteration: "Al-Buruj", nameMeaning: "The Mansions of the Stars", verseCount: 22, revelation: "Meccan" },
  { number: 86, nameArabic: "الطارق", nameTransliteration: "At-Tariq", nameMeaning: "The Morning Star", verseCount: 17, revelation: "Meccan" },
  { number: 87, nameArabic: "الأعلى", nameTransliteration: "Al-A'la", nameMeaning: "The Most High", verseCount: 19, revelation: "Meccan" },
  { number: 88, nameArabic: "الغاشية", nameTransliteration: "Al-Ghashiyah", nameMeaning: "The Overwhelming", verseCount: 26, revelation: "Meccan" },
  { number: 89, nameArabic: "الفجر", nameTransliteration: "Al-Fajr", nameMeaning: "The Dawn", verseCount: 30, revelation: "Meccan" },
  { number: 90, nameArabic: "البلد", nameTransliteration: "Al-Balad", nameMeaning: "The City", verseCount: 20, revelation: "Meccan" },
  { number: 91, nameArabic: "الشمس", nameTransliteration: "Ash-Shams", nameMeaning: "The Sun", verseCount: 15, revelation: "Meccan" },
  { number: 92, nameArabic: "الليل", nameTransliteration: "Al-Layl", nameMeaning: "The Night", verseCount: 21, revelation: "Meccan" },
  { number: 93, nameArabic: "الضحى", nameTransliteration: "Ad-Dhuha", nameMeaning: "The Morning Hours", verseCount: 11, revelation: "Meccan" },
  { number: 94, nameArabic: "الشرح", nameTransliteration: "Ash-Sharh", nameMeaning: "The Relief", verseCount: 8, revelation: "Meccan" },
  { number: 95, nameArabic: "التين", nameTransliteration: "At-Tin", nameMeaning: "The Fig", verseCount: 8, revelation: "Meccan" },
  { number: 96, nameArabic: "العلق", nameTransliteration: "Al-'Alaq", nameMeaning: "The Clot", verseCount: 19, revelation: "Meccan" },
  { number: 97, nameArabic: "القدر", nameTransliteration: "Al-Qadr", nameMeaning: "The Power", verseCount: 5, revelation: "Meccan" },
  { number: 98, nameArabic: "البينة", nameTransliteration: "Al-Bayyinah", nameMeaning: "The Clear Proof", verseCount: 8, revelation: "Medinan" },
  { number: 99, nameArabic: "الزلزلة", nameTransliteration: "Az-Zalzalah", nameMeaning: "The Earthquake", verseCount: 8, revelation: "Medinan" },
  { number: 100, nameArabic: "العاديات", nameTransliteration: "Al-'Adiyat", nameMeaning: "The Courser", verseCount: 11, revelation: "Meccan" },
  { number: 101, nameArabic: "القارعة", nameTransliteration: "Al-Qari'ah", nameMeaning: "The Calamity", verseCount: 11, revelation: "Meccan" },
  { number: 102, nameArabic: "التكاثر", nameTransliteration: "At-Takathur", nameMeaning: "The Rivalry in world increase", verseCount: 8, revelation: "Meccan" },
  { number: 103, nameArabic: "العصر", nameTransliteration: "Al-'Asr", nameMeaning: "The Declining Day", verseCount: 3, revelation: "Meccan" },
  { number: 104, nameArabic: "الهمزة", nameTransliteration: "Al-Humazah", nameMeaning: "The Traducer", verseCount: 9, revelation: "Meccan" },
  { number: 105, nameArabic: "الفيل", nameTransliteration: "Al-Fil", nameMeaning: "The Elephant", verseCount: 5, revelation: "Meccan" },
  { number: 106, nameArabic: "قريش", nameTransliteration: "Quraysh", nameMeaning: "Quraysh", verseCount: 4, revelation: "Meccan" },
  { number: 107, nameArabic: "الماعون", nameTransliteration: "Al-Ma'un", nameMeaning: "The Small Kindnesses", verseCount: 7, revelation: "Meccan" },
  { number: 108, nameArabic: "الكوثر", nameTransliteration: "Al-Kawthar", nameMeaning: "The Abundance", verseCount: 3, revelation: "Meccan" },
  { number: 109, nameArabic: "الكافرون", nameTransliteration: "Al-Kafirun", nameMeaning: "The Disbelievers", verseCount: 6, revelation: "Meccan" },
  { number: 110, nameArabic: "النصر", nameTransliteration: "An-Nasr", nameMeaning: "The Divine Support", verseCount: 3, revelation: "Medinan" },
  { number: 111, nameArabic: "المسد", nameTransliteration: "Al-Masad", nameMeaning: "The Palm Fiber", verseCount: 5, revelation: "Meccan" },
  { number: 112, nameArabic: "الإخلاص", nameTransliteration: "Al-Ikhlas", nameMeaning: "The Sincerity", verseCount: 4, revelation: "Meccan" },
  { number: 113, nameArabic: "الفلق", nameTransliteration: "Al-Falaq", nameMeaning: "The Daybreak", verseCount: 5, revelation: "Meccan" },
  { number: 114, nameArabic: "الناس", nameTransliteration: "An-Nas", nameMeaning: "Mankind", verseCount: 6, revelation: "Meccan" },
]
